#!/usr/bin/env python3
"""Modify zoomus.conf to enforce desired settings."""
import configparser
import sys

config = configparser.RawConfigParser()
config.optionxform = str  # Preserve key casing.
config.read_file(sys.stdin)

if not config.has_section('General'):
    config.add_section('General')
config.set('General', 'xwayland', 'false')

config.write(sys.stdout, space_around_delimiters=False)
